apiVersion: v1
kind: Service
metadata:
  name: productapi-api-service
spec:
  selector:
    app: productservice
  ports:
  - protocol: "TCP"
    port: 50010
    targetPort: 50010
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  selector:
    matchLabels:
      app: productservice
  replicas: 2
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
      - name: productservice
        image: mariappshub/productservice
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 50010